# Ambiente para Programação WEB
# Prof. Vinícius Magnus
# apache + php + mysql + phpmyqdmin
version: "3.8"
# https://docs.docker.com/compose/compose-file/
services:
    www:
        build: .
        container_name: 'www'
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
    db:
        image: mysql:8.0
        container_name: 'db'
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'phpmyadmin'
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: test
        networks:
            - default
networks:
    default:
        driver: bridge
